# hydra config
hydra:
  run:
    dir: /workspace/Two_Stream_PyTorch/logs/${train.version}/${now:%Y-%m-%d}/${now:%H-%M-%S}/${train.clip_duration}_${train.uniform_temporal_subsample_num}_${model.model_depth}

# group by defaults
defaults:
  - optimizer: adam
  - data: seg

model:
  model: "resnet"
  # img_size: 224
  model_class_num: 1 # the class num of model
  model_depth: 50 # choices=[50, 101, 152], help='the depth of used model'

# YOLO:
#   pose_ckpt: "/workspace/Multi_Cue_Video_PyTorch/ckpt/yolov8x-pose.pt"
#   seg_ckpt: "/workspace/Multi_Cue_Video_PyTorch/ckpt/yolov8x-seg.pt"
#   conf: 0.5
#   iou: 0.5

train:
  # Training config
  max_epochs: 50 # numer of epochs of training
  batch_size: 8 # batch size for the dataloader
  clip_duration: 1 # clip duration for the video
  uniform_temporal_subsample_num: 9 # num frame from the clip duration

  gpu_num: 0 # choices=[0, 1], help='the gpu number whicht to train'

  # Transfor_learning
  transfor_learning: True # if use the transformer learning
  train_path: ""
  fold: 0 # the fold of the dataset

  version: "${model.model}" # the version of logger, such data
  log_path: "/workspace/Two_Stream_PyTorch/logs/${model.model}/${now:%Y-%m-%d}/${now:%H-%M-%S}/${train.clip_duration}_${train.uniform_temporal_subsample_num}_${model.model_depth}"
